version: 1.0.0.{build}
skip_branch_with_pr: true
image: Visual Studio 2015
configuration: Release
platform: Any CPU
shallow_clone: true
init:
- ps: git config --global core.autocrlf input
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  APPVEYOR_BUILD_FOLDER: E:\Engineering\Chatters
services: mssql2014
before_build:
- ps: nuget restore
build:
  parallel: true
  verbosity: minimal
deploy:
- provider: GitHub
  description: Beta
  auth_token:
    secure: ZGNVfiS9e+inCnxZuBIwkJEZJjI//VoZVBjWs72e9JHgwODbZbqHACDbyk+Cszd5
  on:
    branch: master
notifications:
- provider: Email
  to:
  - 32xolf@gmail.com
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false
