version: 1.0.0{build}
image: Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  APPVEYOR_BUILD_FOLDER: E:\Engineering\Chatters
  matrix:
  - {}
nuget:
  account_feed: true
  project_feed: true
before_build:
- ps: nuget restore Chatters\ChitChat.sln
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal
deploy:
- provider: GitHub
  release: Chatters-V$(version)
  description: Beta
  auth_token:
    secure: ZGNVfiS9e+inCnxZuBIwkJEZJjI//VoZVBjWs72e9JHgwODbZbqHACDbyk+Cszd5
  on:
    branch: master
