version: 1.0.0{build}
skip_branch_with_pr: true
clone_folder: E:\Engineering\Chatters
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
build:
  project: ChitChat.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: GitHub
  release: Beta
  description: Beta
  auth_token:
    secure: ZGNVfiS9e+inCnxZuBIwkJEZJjI//VoZVBjWs72e9JHgwODbZbqHACDbyk+Cszd5
  on:
    branch: master
notifications:
- provider: Email
  to:
  - 32xolf@gmail.com
  subject: Build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
