version: 1.0.0{build}
image: Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  APPVEYOR_BUILD_FOLDER: E:\Engineering\Chatters
  matrix:
  - {}
before_build:
- ps: nuget restore Chatters\ChitChat.sln
build:
  parallel: true
  verbosity: minimal
deploy:
- provider: GitHub
  release: Beta
  description: Beta
  auth_token:
    secure: ZGNVfiS9e+inCnxZuBIwkJEZJjI//VoZVBjWs72e9JHgwODbZbqHACDbyk+Cszd5
  on:
    branch: master
notifications:
- provider: Email
  to:
  - 32xolf@gmail.com
  subject: Build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
