//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChitChat
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class Client_Details 
    {
        public int Client_Id { get; set; }
        public bool IsOnline { get; set; }
        public bool IsAway { get; set; }
        public Nullable<System.DateTime> Last_Session { get; set; }
        public bool IsLogged { get; set; }
    }
}
