//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChitChat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Info
    {
        public int id { get; set; }
        public string Client_Uname { get; set; }
        public string Client_Upass { get; set; }
        public string Client_emailadd { get; set; }
        public Nullable<System.DateTime> Client_Registered { get; set; }
    }
}
