//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChitChat
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerInfo
    {
        public int Id { get; set; }
        public string servername { get; set; }
        public string ipaddress { get; set; }
        public string port { get; set; }
        public string DNS { get; set; }
    }
}
