//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChitChat
{
    using System;
    using System.Data;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServerEntities : DbContext
    {
        public ServerEntities()
            : base("name=ServerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client_Details> Client_Details { get; set; }
        public virtual DbSet<Client_Info> Client_Info { get; set; }
        public virtual DbSet<ServerInfo> ServerInfoes { get; set; }
    }
}
